[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "numcompute"
version = "0.1.0"
description = "COMP 5004 Project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.26.0",
    "pytest>=7.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["numcompute*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]